// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqisxrctkkukwcmpqvxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaXN4cmN0a2t1a3djbXBxdnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDQ1ODgsImV4cCI6MjA2MzcyMDU4OH0.zAXxQna_gUbJUKdlV2KjYldXYv8YK9FUtRdFG9GDMEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);